services:

  postgres-server:
    image: postgres
    container_name: postgres-server
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: todolist

  adminer:
    image: adminer
    container_name: adminer-console
    restart: always
    ports:
      - 8086:8080