services:
  postgres-server:
    container_name: 'postgres-server'
    image: 'postgres'
    environment:
      - 'POSTGRES_PASSWORD=todolist'
    ports:
      - 5432:5432

  adminer:
    image: adminer
    container_name: adminer-console
    restart: always
    ports:
      - 8085:8080