services:
  mysql:
    container_name: 'guide-mysql'
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=todolist'
      - 'MYSQL_PASSWORD=todolist'
      - 'MYSQL_ROOT_PASSWORD=todolist'
      - 'MYSQL_USER=todolist'
    ports:
      - 3306:3306

  adminer:
    image: adminer
    container_name: adminer-console
    restart: always
    ports:
      - 8086:8080